USE JOBLINK;

ALTER TABLE TB_USER ADD COLUMN TAG VARCHAR(200) NULL DEFAULT NULL COMMENT '标签' AFTER EXPECTED_SALARY;

ALTER TABLE TB_POSITION ADD COLUMN TAG VARCHAR(200) NULL DEFAULT NULL COMMENT '标签' AFTER SALARY_PACKAGE;

ALTER TABLE TB_APPLICATION ADD COLUMN INTERVIEWER_COMMENT_DATE DATETIME NULL DEFAULT NULL COMMENT '面试官反馈日期时间' AFTER INTERVIEWER_COMMENT;
ALTER TABLE TB_APPLICATION ADD COLUMN APPLICANT_COMMENT_DATE DATETIME NULL DEFAULT NULL COMMENT '求职者反馈日期时间' AFTER APPLICANT_COMMENT;

---20150927 start
ALTER TABLE TB_APPLICATION ADD COLUMN `TECH_RATE` INT(11) NULL DEFAULT NULL COMMENT '核心技术评分' AFTER `STATUS`;
ALTER TABLE TB_APPLICATION ADD COLUMN `FRAMEWORK_RATE` INT(11) NULL DEFAULT NULL COMMENT '框架技术评分' AFTER `TECH_RATE`;
ALTER TABLE TB_APPLICATION ADD COLUMN `DATABASE_RATE` INT(11) NULL DEFAULT NULL COMMENT '数据库技术评分' AFTER `FRAMEWORK_RATE`;
ALTER TABLE TB_APPLICATION ADD COLUMN `ENGLISH_RATE` INT(11) NULL DEFAULT NULL COMMENT '英语水平评分' AFTER `DATABASE_RATE`;
ALTER TABLE TB_APPLICATION ADD COLUMN `COMMUNICATION_RATE` INT(11) NULL DEFAULT NULL COMMENT '交流能力评分' AFTER `ENGLISH_RATE`;
ALTER TABLE TB_APPLICATION ADD COLUMN `MANAGEMENT_RATE` INT(11) NULL DEFAULT NULL COMMENT '管理能力评分' AFTER `COMMUNICATION_RATE`;
---20150927 end

---20151007 start
ALTER TABLE TB_USER ADD COLUMN `VISA` VARCHAR(50) NULL DEFAULT NULL COMMENT '持有签证' AFTER `EXPECTED_SALARY`;
ALTER TABLE TB_USER ADD COLUMN `VISA_EXPIRED_DATE` DATE NULL DEFAULT NULL COMMENT '签证有效期截止日期' AFTER `VISA`;
---20151007 end

---20151014 start
ALTER TABLE TB_POSITION ADD COLUMN `IF_OPEN` TINYINT(1) NOT NULL COMMENT '是否开放' AFTER `EXPIRED_DATE`;
ALTER TABLE TB_POSITION ADD COLUMN `IF_VALID` TINYINT(1) NOT NULL COMMENT '是否有效' AFTER `IF_OPEN`;
UPDATE TB_POSITION SET IF_OPEN = 1, IF_VALID = 1;

ALTER TABLE TB_POSITION CHANGE COLUMN `IF_OPEN` `IF_OPEN` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否开放';
ALTER TABLE TB_POSITION CHANGE COLUMN `IF_VALID` `IF_VALID` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否有效';
---20151014 end

---20151028 start
ALTER TABLE TB_USER CHANGE COLUMN `TAG` `TAG` VARCHAR(200) NULL DEFAULT NULL COMMENT '标签' AFTER `VISA_EXPIRED_DATE`;
ALTER TABLE TB_EMPLOYER ADD COLUMN `CITY` VARCHAR(20) DEFAULT NULL COMMENT '所在城市' AFTER `SCALE`;
UPDATE TB_EMPLOYER SET CITY = '上海' WHERE ADDRESS IS NOT NULL;
---UPDATE TB_EMPLOYER SET CITY = '北京' WHERE ADDRESS LIKE '%北京%';

ALTER TABLE TB_POSITION ADD COLUMN `CITY` VARCHAR(20) DEFAULT NULL COMMENT '所在城市' AFTER `TITLE`;
ALTER TABLE TB_POSITION ADD COLUMN `ADDRESS` VARCHAR(200) DEFAULT NULL COMMENT '工作地点' AFTER `CITY`;
UPDATE TB_POSITION SET CITY = LOCATION WHERE LOCATION IS NOT NULL;
ALTER TABLE TB_POSITION DROP COLUMN `LOCATION`;
---20151028 end

---20151101 start
ALTER TABLE TB_USER ADD COLUMN `IF_TOBE_SEACHED` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否愿意被招聘方找到' AFTER `PROFILE_URL_EN`;
---20151101 end

---20151104 start
ALTER TABLE TB_USER CHANGE COLUMN `IF_TOBE_SEACHED` `IF_TOBE_SEARCHED` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '是否愿意被招聘方找到';
---20151104 end


---Srpint2 start
---20151109 start
CREATE TABLE TB_SUGGESTION (
  ID VARCHAR(50) NOT NULL COMMENT 'ID',
  SUGGESTION_TYPE VARCHAR(20) NOT NULL COMMENT '意见类别',
  SUGGESTION_CONTENT TEXT NOT NULL COMMENT '反馈意见内容',
  USER_IP VARCHAR(20) DEFAULT NULL COMMENT '提交人IP地址',
  USER_CITY VARCHAR(20) DEFAULT NULL COMMENT '提交人所在城市',
  SUBMIT_TIME DATETIME NOT NULL COMMENT '提交日期时间',
  PRIMARY KEY (ID),
  INDEX IDX_SUGGESTION_CITY(USER_CITY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='反馈意见表';
---20151109 end
---Srpint2 end


---Srpint3 start
---20151118 start
ALTER TABLE TB_POSITION CHANGE COLUMN `TITLE` `TITLE` VARCHAR(100) NOT NULL COMMENT '职位名称';

ALTER TABLE TB_POSITION ADD COLUMN `SALARY_TYPE` INT(11) NOT NULL DEFAULT 1 COMMENT '工资类型  1 月薪 2 年薪' AFTER `REQUIREMENT`;
---20151118 end

---Srpint3 end